// <auto-generated />
using System;
using Lumiere.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lumiere.API.Migrations
{
    [DbContext(typeof(LumiereContext))]
    [Migration("20260211201733_SessoesNullIgnoredByJson")]
    partial class SessoesNullIgnoredByJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lumiere.Models.Assento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coluna")
                        .HasColumnType("int");

                    b.Property<string>("Fileira")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoAssento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Assentos");
                });

            modelBuilder.Entity("Lumiere.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificacaoIndicativa")
                        .HasColumnType("int");

                    b.Property<string>("Direcao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Distribuidora")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("Lumiere.Models.FormatoSessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("FormatosSessao");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "2D"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "3D"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "IMAX"
                        });
                });

            modelBuilder.Entity("Lumiere.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Comédia"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Terror"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Ficção"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Animação"
                        });
                });

            modelBuilder.Entity("Lumiere.Models.Ingresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SessaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoIngressoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssentoId");

                    b.HasIndex("SessaoId");

                    b.HasIndex("TipoIngressoId");

                    b.ToTable("Ingressos");
                });

            modelBuilder.Entity("Lumiere.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("NumeroColunas")
                        .HasColumnType("int");

                    b.Property<int>("NumeroLinhas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Lumiere.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataHoraFim")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataHoraInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FilmeId")
                        .HasColumnType("int");

                    b.Property<int>("FormatoSessaoId")
                        .HasColumnType("int");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PrecoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmeId");

                    b.HasIndex("FormatoSessaoId");

                    b.HasIndex("SalaId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("Lumiere.Models.TipoIngresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DescontoPercentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("TiposIngresso");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescontoPercentual = 0.00m,
                            Nome = "Inteira"
                        },
                        new
                        {
                            Id = 2,
                            DescontoPercentual = 50.00m,
                            Nome = "Meia"
                        },
                        new
                        {
                            Id = 3,
                            DescontoPercentual = 50.00m,
                            Nome = "Estudante"
                        },
                        new
                        {
                            Id = 4,
                            DescontoPercentual = 50.00m,
                            Nome = "Idoso"
                        },
                        new
                        {
                            Id = 5,
                            DescontoPercentual = 30.00m,
                            Nome = "Criança"
                        });
                });

            modelBuilder.Entity("Lumiere.Models.Assento", b =>
                {
                    b.HasOne("Lumiere.Models.Sala", "Sala")
                        .WithMany("Assentos")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Lumiere.Models.Filme", b =>
                {
                    b.HasOne("Lumiere.Models.Genero", "Genero")
                        .WithMany("Filmes")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Lumiere.Models.Ingresso", b =>
                {
                    b.HasOne("Lumiere.Models.Assento", "Assento")
                        .WithMany("Ingressos")
                        .HasForeignKey("AssentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lumiere.Models.Sessao", "Sessao")
                        .WithMany("Ingressos")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Models.TipoIngresso", "TipoIngresso")
                        .WithMany("Ingressos")
                        .HasForeignKey("TipoIngressoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assento");

                    b.Navigation("Sessao");

                    b.Navigation("TipoIngresso");
                });

            modelBuilder.Entity("Lumiere.Models.Sessao", b =>
                {
                    b.HasOne("Lumiere.Models.Filme", "Filme")
                        .WithMany("Sessoes")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Models.FormatoSessao", "FormatoSessao")
                        .WithMany("Sessoes")
                        .HasForeignKey("FormatoSessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lumiere.Models.Sala", "Sala")
                        .WithMany("Sessoes")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Filme");

                    b.Navigation("FormatoSessao");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Lumiere.Models.Assento", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("Lumiere.Models.Filme", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Lumiere.Models.FormatoSessao", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Lumiere.Models.Genero", b =>
                {
                    b.Navigation("Filmes");
                });

            modelBuilder.Entity("Lumiere.Models.Sala", b =>
                {
                    b.Navigation("Assentos");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("Lumiere.Models.Sessao", b =>
                {
                    b.Navigation("Ingressos");
                });

            modelBuilder.Entity("Lumiere.Models.TipoIngresso", b =>
                {
                    b.Navigation("Ingressos");
                });
#pragma warning restore 612, 618
        }
    }
}
